spring:
  session:
    redis:
      repository-type: indexed
      save-mode: always
      namespace: lightlyIM:session
    timeout: 5m
  application:
    name: LightlyIM
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:lightlyIM;IGNORECASE=TRUE;DATABASE_TO_UPPER=false
    url: jdbc:h2:file:./data/LightlyIMDB;IGNORECASE=TRUE;DATABASE_TO_UPPER=false;AUTO_SERVER=true
    username: ZLinux
    password: ZLinux
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
  data:
    redis:
      port: 6379
      database: 0
      host: localhost
      password:
      lettuce:
        pool:
          enabled: true
          max-active: 20
          max-idle: 10

  security:
    user:
      name: user
      password: admin
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    time-zone: Asia/Shanghai
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitRoot
    password: rabbitRoot
logging:
  level:
    root: info
    org.springframework.security: debug
    org.mybatis: debug
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
