spring:
  application:
    name: LightlyIM
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    org.springframework.security: debug
    org.mybatis: debug
