spring:
  application:
    name: LightlyIM
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:lightlyIM;IGNORECASE=TRUE;DATABASE_TO_UPPER=false
    url: jdbc:h2:file:./src/main/resources/LightlyIMDB;IGNORECASE=TRUE;DATABASE_TO_UPPER=false;AUTO_SERVER=true
    username: ZLinux
    password: ZLinux
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
  data:
    redis:
      port: 6379
      database: 0
      host: localhost
      password:
      jedis:
        pool:
          max-active: 20
          max-wait: 100ms
      connect-timeout: 1000ms
  security:
    user:
      password: admin
logging:
  level:
    root: info
    org.springframework.security: debug
    org.mybatis: debug
